# kubectl apply -f .\jasperreports-server-k8s.yml
# kubectl delete -f .\jasperreports-server-k8s.yml
apiVersion: v1
kind: Service
metadata:
  name: jasperserver-pro
  labels:
    app: jasperserver-pro
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: jasperserver-pro
  selector:
    app: jasperserver-pro
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jasperserver-pro
  labels:
    app: jasperserver-pro
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jasperserver-pro
    spec:
      containers:
      - name: jasperserver-pro
        image: jasperserver-pro:7.5.0
        env:
          - name: DB_HOST
            value: postgresql
          - name: DB_NAME
            value: jasperserver
          - name: JRS_LICENSE
            value: "/usr/local/share/jasperserver-pro-secrets/license"
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          - name: https
            containerPort: 8443
            protocol: TCP
        volumeMounts:
        - name: license
          mountPath: "/usr/local/share/jasperserver-pro-secrets/license"
          readOnly: true
        # web app accesses the keystore secret directly
        # maintained by the init container
        - name: keystore-files-secret
          mountPath: "/usr/local/share/jasperserver-pro/keystore"
          readOnly: true
        - name: jasperserver-pro-volume
          mountPath: "/usr/local/share/jasperserver-pro"
          readOnly: true
      initContainers:
      - name: init
        image: jasperserver-pro-cmdline:k8s-7.5.0
        env:
          - name: DB_HOST
            value: postgresql
          - name: DB_NAME
            value: jasperserver
          - name: JRS_LOAD_SAMPLES
            value: "true"
          - name: JRS_LICENSE
            value: "/usr/local/share/jasperserver-pro-secrets/license"
          #- name: KEYSTORE_SECRET_NAME
          #  value: "jasperserver-pro-jrsks"
        volumeMounts:
        - name: license
          mountPath: "/usr/local/share/jasperserver-pro-secrets/license"
          readOnly: true
        # have the keystore secret under its own path.
        # init container will maintain the keystore files in 
        # /usr/local/share/jasperserver-pro/keystore
        # and update the secret if needed
        - name: keystore-files-secret
          mountPath: "/usr/local/share/jasperserver-pro-secrets/jasperserver-pro-jrsks"
          readOnly: true
        - name: jasperserver-pro-volume
          mountPath: "/usr/local/share/jasperserver-pro"
          readOnly: false
      volumes:
      - name: license
        secret:
          secretName: jasperserver-pro-license
      - name: keystore-files-secret
        secret:
          secretName: jasperserver-pro-jrsks
      - name: jasperserver-pro-volume
        emptyDir: {}
