apiVersion: v1
kind: PersistentVolume
metadata:
  name: jasperreports-server-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/C/Dev/k8svolume"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jasperreports-server-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

